### ISSUE TITLE
Setup - Set up AWS Infrastructure with Terraform

### ISSUE THREAD

**Issue by eulloa10** [eulloa10/financial-data-pipeline#16]
#### Tasks:
- [x] Provision AWS resources for S3, Redshift/RDS, Glue, Lambda, and SES.
- [x] Configure necessary IAM roles and permissions.
- [x] Define S3 bucket, Redshift/RDS database, and Glue jobs.
