### ISSUE TITLE
Setup - Set up Terraform for the project

### ISSUE THREAD

**Issue by eulloa10** [eulloa10/financial-data-pipeline#17]
#### Tasks
- [x] Install and configure Terraform.
- [x] Create configuration files for provisioning the AWS infrastructure.
- [x] Test Terraform scripts to ensure correct provisioning of resources.
