### ISSUE TITLE
Data Warehouse - Set Up RDS for Data Storage

### ISSUE THREAD

**Issue by eulloa10** [eulloa10/financial-data-pipeline#6]
#### Description:
Set up an Amazon RDS to store transformed financial and economic data.

#### Tasks:
  - [x] Create an Amazon RDS instance.
  - [x] Define tables based on the transformed data (e.g., indicator names, timestamps, values).
  - [x] Define table for indicator metadata (name, description, etc.)
  - [x] Configure connection between Glue and RDS for data loading.
